[package]
name = "rdhcp"
version = "0.0.1"
description = "A Rust implementation of the DHCP protocol."
authors = ["Kim Nilsson <kim@wayoftao.net>"]
license = "MIT"
homepage = "https://github.com/nilssonk/rdhcp"
repository = "https://github.com/nilssonk/rdhcp"
edition = "2021"

[dependencies]
